const db = [
  {
    progLang: "javascript",
    color: "red",
    id: 1,
    completed: false,
  },
  {
    progLang: "python",
    color: "green",
    id: 2,
    completed: false,
  },
  {
    progLang: "java",
    color: "blue",
    id: 3,
    completed: false,
  },
  {
    progLang: "c++",
    color: "yellow",
    id: 4,
    completed: false,
  },
  {
    progLang: "c#",
    color: "magenta",
    id: 5,
    completed: false,
  },
  {
    progLang: "swift",
    color: "cyan",
    id: 6,
    completed: false,
  },
  {
    progLang: "ruby",
    color: "purple",
    id: 7,
    completed: false,
  },
  {
    progLang: "php",
    color: "orange",
    id: 8,
    completed: false,
  },
  {
    progLang: "go",
    color: "teal",
    id: 9,
    completed: false,
  },
  {
    progLang: "rust",
    color: "navy",
    id: 10,
    completed: false,
  },
  {
    progLang: "kotlin",
    color: "lime",
    id: 11,
    completed: false,
  },
  {
    progLang: "typescript",
    color: "violet",
    id: 12,
    completed: false,
  },
  {
    progLang: "perl",
    color: "brown",
    id: 13,
    completed: false,
  },
  {
    progLang: "haskell",
    color: "grey",
    id: 14,
    completed: false,
  },
  {
    progLang: "scala",
    color: "pink",
    id: 15,
    completed: false,
  },
  {
    progLang: "julia",
    color: "silver",
    id: 16,
    completed: false,
  },
  {
    progLang: "pascal",
    color: "coral",
    id: 17,
    completed: false,
  },
  {
    progLang: "lua",
    color: "gold",
    id: 18,
    completed: false,
  },
  {
    progLang: "assembly",
    color: "lavender",
    id: 19,
    completed: false,
  },
  {
    progLang: "f#",
    color: "beige",
    id: 20,
    completed: false,
  },
  {
    progLang: "bash",
    color: "lightgreen",
    id: 21,
    completed: false,
  },
  {
    progLang: "livescript",
    color: "lightblue",
    id: 22,
    completed: false,
  },
  {
    progLang: "q",
    color: "lightyellow",
    id: 23,
    completed: false,
  },
  {
    progLang: "dart",
    color: "olive",
    id: 24,
    completed: false,
  },
  {
    progLang: "delphi",
    color: "turquoise",
    id: 25,
    completed: false,
  },
  {
    progLang: "cobol",
    color: "crimson",
    id: 26,
    completed: false,
  },
  {
    progLang: "c",
    color: "skyblue",
    id: 27,
    completed: false,
  },
  {
    progLang: "objective-c",
    color: "coral",
    id: 28,
    completed: false,
  },
  {
    progLang: "grails",
    color: "darkgray",
    id: 29,
    completed: false,
  },
  {
    progLang: "factor",
    color: "darkblue",
    id: 30,
    completed: false,
  },
];

export default db;
